[versions]
wat = { strictly = "1.1.0.34-beta" }

# wat plugins
usbr-plugin = { strictly = "0.0.93" }
cequal-plugin = { strictly = "2.4.1" }
ressim-plugin = { strictly = "2.2.1" }

# ressim gvdl plugin jar
ressim-gvdl = { strictly = "4.0.1.134-Beta" }

# usbr git tool
usbr-git = { strictly = "3.3.6" }

# ResSim
ressim-zip = { strictly = "4.0.1.134-Beta-win-x86_64" }

# jasper fonts jar
jasper-fonts = { strictly = "1.0" }

# W2 natives
w2pre = { strictly = "4.0-win-x86_64" }
w2post = { strictly = "3.0-win-x86_64" }
cequalw2-exe = { strictly = "4.0-win-x86_64" }
cequalw2-tcd-exe = { strictly = "4.1-TCD-mp-win-x86_64" }
cequalw2-tcd081721-exe = { strictly = "TCD-081721" }
cequalw2-folsom-exe = { strictly = "4.5-64-Folsom" }

cequalw2-v45-exe = { strictly = "4.5-win-x86_64" }
cequalw2preconsole-v45-exe = { strictly = "4.5-win-x86_64" }
cequalw2pre-v45-exe = { strictly = "4.5-win-x86_64" }

jackson-version = { strictly = "2.13.0" }

# JHDF5 needed for some scripts
jhdf5 = { strictly = "1.0-win-x86_64" }
jarhdf5 = { strictly = "2.11.0" }


[libraries]
# usbr plugins
actionpanel-plugin = { module = "usbr.wat.plugins:usbr-actionpanel-plugin", version.ref = "usbr-plugin" }
comparison-report-plugin = { module = "usbr.wat.plugins:usbr-comparison-report", version.ref = "usbr-plugin" }
simulation-report-plugin = { module = "usbr.wat.plugins:usbr-simulation-report", version.ref = "usbr-plugin" }
forecast-report-plugin = {module = "usbr.wat.plugins:usbr-forecast-report", version.ref = "usbr-plugin"}

# wat plugins
cequal-plugin = { module = "mil.army.usace.hec.wat:wat-plugin-cequalw2", version.ref = "cequal-plugin" }
ressim-plugin = { module = "mil.army.usace.hec.wat:wat-plugin-ressim-4.0", version.ref = "ressim-plugin" }
ressim-gvdl = { module = "mil.army.usace.hec.ressim:ressim-gvdl-util", version.ref = "ressim-gvdl" }

jasper-fonts = { module = "gov.usbr:usbr-jasper-fonts", version.ref = "jasper-fonts" }

jackson-json = { module = "com.fasterxml.jackson.datatype:jackson-datatype-json-org", version.ref = "jackson.version" }

# JHDF Needed for some scripts
jhdf5-win-x8664 = { module = "mil.army.usace.hec.ressim:jhdf5-native", version.ref = "jhdf5" }
jarhdf5 = { module = "ncsa.hdf:jarhdf5", version.ref = "jarhdf5" }

[bundles]
wat-plugins = ["cequal-plugin", "ressim-plugin"]
usbr-plugins = ["actionpanel-plugin", "comparison-report-plugin", "simulation-report-plugin", "forecast-report-plugin"]
