[versions]
wat = { strictly = "1.1.0.34-beta-win-x86_64" }

# wat plugins
usbr-plugin = "main-SNAPSHOT"
cequal-plugin = { strictly = "3.0.2" }
ressim-plugin = { strictly = "2.2.1" }

# ressim gvdl plugin jar
ressim-gvdl = { strictly = "4.0.1.188-Beta" }

# usbr git tool
usbr-git = "master-SNAPSHOT"

# ResSim
ressim-zip = { strictly = "4.0.1.188-Beta-win-x86_64" }

# jasper fonts jar
jasper-fonts = { strictly = "1.0" }

# W2 natives
w2pre = { strictly = "4.0-win-x86_64" }
w2post = { strictly = "3.0-win-x86_64" }
cequalw2-exe = { strictly = "4.0-win-x86_64" }
cequalw2-tcd-exe = { strictly = "4.1-TCD-mp-win-x86_64" }
cequalw2-tcd081721-exe = { strictly = "TCD-081721" }
cequalw2-folsom-exe = { strictly = "4.5-64-Folsom" }

cequalw2-v45-exe = { strictly = "4.5-win-x86_64" }
cequalw2preconsole-v45-exe = { strictly = "4.5-win-x86_64" }
cequalw2pre-v45-exe = { strictly = "4.5-win-x86_64" }

jackson-version = { strictly = "2.13.0" }

# JHDF5 needed for some scripts
jhdf5 = { strictly = "1.0-win-x86_64" }
jarhdf5 = { strictly = "2.11.0" }


[libraries]
# usbr plugins
actionpanel-plugin = { module = "usbr.wat.plugins:usbr-actionpanel-plugin", version.ref = "usbr-plugin" }
comparison-report-plugin = { module = "usbr.wat.plugins:usbr-comparison-report", version.ref = "usbr-plugin" }
simulation-report-plugin = { module = "usbr.wat.plugins:usbr-simulation-report", version.ref = "usbr-plugin" }
forecast-report-plugin = {module = "usbr.wat.plugins:usbr-forecast-report", version.ref = "usbr-plugin"}

cequalw2-v5-tcd = { module = "edu.pdx.ce.w2:w2", version = "v5-tcd-2025-09-26"}

# WAT Install
wat-install = { module = "mil.army.usace.hec.wat:wat-install-package-rss-4.0", version.ref = "wat" }

# W2 Exes
w2-pre = { module = "edu.pdx.ce.w2:w2-pre", version.ref = "w2pre" }
w2-post = { module = "edu.pdx.ce.w2:w2-post", version.ref = "w2post" }
cequalw2 = { module = "edu.pdx.ce.w2:w2", version.ref = "cequalw2-exe" }
cequalw2-tcd = { module = "edu.pdx.ce.w2:w2", version.ref = "cequalw2-tcd-exe" }
cequalw2-tcd0817 = { module = "edu.pdx.ce.w2:w2", version.ref = "cequalw2-tcd081721-exe" }
cequalw2-v45 = { module = "edu.pdx.ce.w2:w2", version.ref = "cequalw2-v45-exe" }
cequalw2preconsole-v45 = { module = "edu.pdx.ce.w2:w2-pre-console", version.ref = "cequalw2preconsole-v45-exe" }
cequalw2pre-v45 = { module = "edu.pdx.ce.w2:w2-pre", version.ref = "cequalw2pre-v45-exe" }
cequalw2-folsom = { module = "edu.pdx.ce.w2:w2", version.ref = "cequalw2-folsom-exe" }

# ResSim
ressim-install = { module = "mil.army.usace.hec.ressim:hec-ressim", version.ref = "ressim-zip" }

# USBR Plugins/Tools
usbr-actionpanel-jasper = { module = "usbr.wat.plugins:usbr-actionpanel-jasper", version.ref = "usbr-plugin" }
usbr-actionpanel-python = { module = "usbr.wat.plugins:usbr-actionpanel-python", version.ref = "usbr-plugin" }
usbr-wtmp-git = { module = "usbr.wat.plugins:usbr-wtmp-git-tool", version.ref = "usbr-git" }

# wat plugins
cequal-plugin = { module = "mil.army.usace.hec.wat:wat-plugin-cequalw2", version.ref = "cequal-plugin" }
ressim-plugin = { module = "mil.army.usace.hec.wat:wat-plugin-ressim-4.0", version.ref = "ressim-plugin" }
ressim-gvdl = { module = "mil.army.usace.hec.ressim:ressim-gvdl-util", version.ref = "ressim-gvdl" }

jasper-fonts = { module = "gov.usbr:usbr-jasper-fonts", version.ref = "jasper-fonts" }

jackson-json = { module = "com.fasterxml.jackson.datatype:jackson-datatype-json-org", version.ref = "jackson.version" }

# JHDF Needed for some scripts
jhdf5-win-x8664 = { module = "mil.army.usace.hec.ressim:jhdf5-native", version.ref = "jhdf5" }
jarhdf5 = { module = "ncsa.hdf:jarhdf5", version.ref = "jarhdf5" }

[bundles]
wat-plugins = ["cequal-plugin", "ressim-plugin"]
usbr-plugins = ["actionpanel-plugin", "comparison-report-plugin", "simulation-report-plugin", "forecast-report-plugin"]
